### ISSUE TITLE
Windows Build?

### ISSUE THREAD

**Issue by omperus** [zweicoder/WhatsApp-Desktop#4]
I don't know much about coding and i was wondering if the setup file could be uploaded like in the aluxian distro, thanks.

**Comment by zweicoder** [comment]
@omperus Hey I added a link onto the `README`, go try it out and update me whether it works :)

**Comment by omperus** [comment]
Works great, thanks a lot! :D

**Comment by omperus** [comment]
After some days using it, i found a bug.
The first time i open it after restarting windows it shows me that "We recommend using WhatsApp Web with one of the following browsers", but it fixes itself by restarting the program so there is that.
